;*======================================================================*
;*                TITLE:                  WORLD.INC                     *
;*                Function:               World definitions (MOBS)      *
;*                                                                      *
;*                Project #:              JAGUAR                        *
;*                Programmer:             Andrew J Burgess              *
;*                                                                      *
;*              COPYRIGHT 1993 Atari Computer Corporation               *
;*          UNATHORIZED REPRODUCTION, ADAPTATION, DISTRIBUTION,         *
;*          PERFORMANCE OR DISPLAY OF THIS COMPUTER PROGRAM OR          *
;*        THE ASSOCIATED AUDIOVISUAL WORK IS STRICTLY PROHIBITED.       *
;*                            ALL RIGHTS RESERVED.                      *
;*                                                                      *
;*======================================================================*

;*======================================================================*
;*
;*	STATE TABLE VALUES
;*
;*======================================================================*

;* DEMO STATES
INITLETTER_STATE	=	0
LETTER_STATE		=	1
DEMOOVER_STATE		=	2

;* LETTER STATES
INIT_L			=	0
PLAY_L			=	1
BONUS_L			=	2
OVER_L			=	3

;*======================================================================*
;*                                 EOF                                  *
;*======================================================================*
