
#====================================================================
#       Macro & Assembler flags
#====================================================================

STADDR = 802000
MACFLAGS = -fb -g
ALNFLAGS = -v -v -e -g -l -a $(STADDR) x 4000

#====================================================================
#       Default Rules
#====================================================================
.SUFFIXES:      .o .s

.s.o:
	mac $(MACFLAGS) $*

#====================================================================
#       EXECUTABLES
#====================================================================

OBJ =   testrgb.o test.o intserv.o vidinit.o jlister.o clearjag.o
 
testrgb.abs: $(OBJ)
	aln $(ALNFLAGS) $(OBJ)

test.o: test.s vidstuff.inc

jlister.o: jlister.s vidstuff.inc

